"""Initial migration

Revision ID: abc770005255
Revises: d86b8c36b9f6
Create Date: 2024-05-13 20:40:39.901186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc770005255'
down_revision = 'd86b8c36b9f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(length=100), nullable=False))

    # ### end Alembic commands ###
