"""Initial migration

Revision ID: d86b8c36b9f6
Revises: 54a3e89adb7b
Create Date: 2024-05-13 20:36:03.743142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86b8c36b9f6'
down_revision = '54a3e89adb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
