"""Initial migration

Revision ID: e7565cf6e093
Revises: abc770005255
Create Date: 2024-05-13 21:20:43.090076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7565cf6e093'
down_revision = 'abc770005255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('audio_path', sa.String(length=200), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('audio_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_file', sa.VARCHAR(length=100), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('audio_path')
        batch_op.drop_column('audio_filename')

    # ### end Alembic commands ###
